{% set name = "tinyflux" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tinyflux-{{ version }}.tar.gz
  sha256: e30e54f9aaa19c81a7ef43992e34d12cb99d37e1bf50df0feea3c1d43496747a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=42
  run:
    - python >=3.7

test:
  imports:
    - tinyflux
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/citrusvanilla/tinyflux
  summary: The Tiny Time-Series Database Optimized for Your Happiness
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
