{% set name = "tinyflux" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tinyflux-{{ version }}.tar.gz
  sha256: d8ed7d0fd8d8bfd2b1326a5d891f192fcdf1c54678bbeff3535d91ee8875a2eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  imports:
    - tinyflux
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/citrusvanilla/tinyflux
  summary: The Tiny Time-Series Database Optimized for Your Happiness
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
