{% set name = "tinyflux" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tinyflux-{{ version }}.tar.gz
  sha256: aa2f437eed158dea77451539fd883f19e751209f0fa711dbbe9bfcfa1c4405cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=42
  run:
    - python >=3.7

test:
  imports:
    - tinyflux
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/citrusvanilla/tinyflux
  summary: The Tiny Time-Series Database Optimized for Your Happiness
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
