schema_version: 1

context:
  name: tinyflux
  version: "1.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tinyflux-${{ version }}.tar.gz
  sha256: 64240e0ec303fb371077e86c92955072261c13cca25c285de0eb7eab8cdc18a5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=42
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - tinyflux
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Tiny Time-Series Database Optimized for Your Happiness
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/citrusvanilla/tinyflux

extra:
  recipe-maintainers:
    - thewchan
